### ISSUE TITLE
Compare result

### ISSUE THREAD

**Issue by gilly3** [iceddev/bcrypt-as-promised#1]
I like having a promise version of bcrypt, but I want to suggest an API change.  The `.compare()` method should contain a boolean in the resolved promise indicating match/no match, and a rejected promise should be reserved for errors only.
- This more closely maps to the API exposed by [bcrypt](https://github.com/ncb000gt/node.bcrypt.js)
- This is a better use of promises.

In my app, I will take different actions if there is an error than if there is a mismatched password.

I would recommend changing the interface and bumping the version to 2, since this would be a breaking change.

**Comment by phated** [comment]
This comes down to a philosophical discussion.  We tend to think that an incorrect password is an exceptional case and should reject the promise because your application logic should be happy-path only.

Instead of returning happy path for an incorrect compare, I think the promise should reject with a custom error class so you can use something like [`when`'s .catch() with a predicate](https://github.com/cujojs/when/blob/master/docs/api.md#promisecatch) to return to your happy-path upon failure.

**Comment by tcurdt** [comment]
I am with @gilly3 on that. An incorrect compare itself is no exception - you are assuming a use case for a general purpose library here. And even for the password case - passing state via exceptions has never been a good idea. But that is indeed more of a philosophical discussion.

**Comment by phated** [comment]
The code for not rejecting would look something like:

``` js
bcrypt.compare('my password', someHash)
  .then(function(success){
    if(success){
      return happyPath();
    } else {
      return sadPath();
    }
  })
  .catch(errorPath);
```

But with a custom error class and predicate filtering, it would look like:

``` js
bcrypt.compare('my password', someHash)
  .then(happyPath)
  .catch(bcrypt.MISMATCH, sadPath) 
  .catch(errorPath);
```

Which I still believe is the ~~correct~~ better implementation.

**Comment by tcurdt** [comment]
"correct" is surely not the right word here - and this reads pretty well, too

```
bcrypt.compare('my password', someHash)
  .then(function(success){
    return success ? happyPath() : sadPath()
  })
  .catch(errorPath)
```

But it's ok to disagree - and wrapping `bcrypt` is just a few lines of code anyway.

**Comment by phated** [comment]
Sorry, meant to say better, since it is our opinion.  The ternary operator in your updated example doesn't remove the need for the extra closure, which is the part we try to avoid when writing promise chains.

**Comment by gilly3** [comment]
The custom error type offers no benefit when using native Promises.

[bcrypt-then](https://www.npmjs.com/package/bcrypt-then) implements the API I'm looking for.  I've been using it for months without issues.  It's good to have options.  Different strokes for different folks and all that.

**Comment by phated** [comment]
:+1: this module definitely exposes the `when` API, if that's not what you are looking for, then your option is a good choice.
